version: '3.8'

services:
  server:                                               # service name 
    # build:
    #   context: .
    #   dockerfile: Dockerfile                          # Optional if your Dockerfile is named 'Dockerfile'
    image: akdevanurag/simple-node-img-jenkins:latest   # Image will be tagged locally as "node-img"
    container_name: server                              # Custom container name
    ports:
      - "8085:8085"
